# Generated by Django 5.0.3 on 2024-04-08 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="dueDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 8, 20, 39, 37, 324543)
            ),
        ),
    ]
