# Generated by Django 5.0.3 on 2024-04-08 20:52

import courses.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_assignment_duedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="dueDate",
            field=courses.models.CustomDateTimeField(auto_now_add=True),
        ),
    ]
