# Generated by Django 5.0.3 on 2024-04-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_course_instructors_course_tas_alter_course_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="answeredStatus",
        ),
        migrations.AddField(
            model_name="question",
            name="answeredStatus",
            field=models.BooleanField(default=False),
        ),
    ]
