# Generated by Django 5.0.3 on 2024-04-24 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_remove_answer_answeredstatus_question_answeredstatus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answerer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answerer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asmId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asmId",
                        to="courses.assignment",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="questions", to="courses.question"
                    ),
                ),
            ],
        ),
    ]
