# Generated by Django 5.0.3 on 2024-04-24 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_cluster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="questions",
        ),
    ]
