# Generated by Django 5.0.3 on 2024-04-24 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_cluster_questions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="answerer",
        ),
        migrations.AddField(
            model_name="cluster",
            name="answerers",
            field=models.ManyToManyField(
                related_name="answerers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
