# Generated by Django 5.0.3 on 2024-04-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_remove_cluster_answerer_cluster_answerers"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="numSubmissions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assignment",
            name="percentAnswered",
            field=models.FloatField(default=0),
        ),
    ]
