# Generated by Django 5.0.3 on 2024-04-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_cluster_claimedquestions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="claimedQuestions",
        ),
        migrations.AddField(
            model_name="question",
            name="claimedStatus",
            field=models.BooleanField(default=False),
        ),
    ]
