# Generated by Django 5.0.3 on 2024-04-30 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_remove_cluster_claimedquestions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="answerers",
        ),
    ]
