# Generated by Django 5.0.3 on 2024-03-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveBigIntegerField(
                blank=True,
                choices=[(1, "Instructor"), (2, "TA"), (3, "Student")],
                null=True,
            ),
        ),
    ]
