# Generated by Django 5.0.3 on 2024-03-27 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_reset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="courseId",
        ),
        migrations.RemoveField(
            model_name="question",
            name="assignmentId",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
