# Generated by Django 5.0.3 on 2024-04-09 02:37

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0005_remove_assignment_courseid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorUserPermissions",
            fields=[
                (
                    "permission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_students", "Can view all students"),
                    ("edit_students", "Can edit all users"),
                    ("view_questions", "Can view all questions"),
                    ("view_answers", "Can view all answers"),
                    ("assign_questions", "Can assign questions to TAs"),
                    ("edit_answers", "Can edit answers"),
                    ("publish_assignment", "Can publish assignment"),
                ),
            },
            bases=("auth.permission",),
            managers=[
                ("objects", django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
